from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parent
DEFAULT_MARKDOWN_REPORT_PATH = REPO_ROOT / "docs" / "asset-acceptance-report.md"
DEFAULT_JSON_REPORT_PATH = REPO_ROOT / "docs" / "asset-acceptance-report.json"


def configure_console_streams() -> None:
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if callable(reconfigure):
            reconfigure(errors="replace")


def run_command(command: list[str]) -> dict[str, Any]:
    completed = subprocess.run(
        command,
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    stdout = (completed.stdout or "").strip()
    stderr = (completed.stderr or "").strip()
    return {
        "command": command,
        "ok": completed.returncode == 0,
        "returncode": completed.returncode,
        "stdout": stdout,
        "stderr": stderr,
    }


def summarize_asset_doctor(stdout: str) -> dict[str, Any]:
    summary = {
        "placeholders_pending": None,
        "replaced": None,
        "missing_assets": None,
        "missing_audio": None,
    }
    for line in stdout.splitlines():
        line = line.strip()
        if not line.startswith("Summary:"):
            continue
        payload = line.split("Summary:", 1)[1]
        for chunk in payload.split(","):
            if "=" not in chunk:
                continue
            key, value = chunk.strip().split("=", 1)
            key = key.strip()
            if key in summary:
                try:
                    summary[key] = int(value.strip())
                except ValueError:
                    summary[key] = value.strip()
        break
    return summary


def summarize_docs_doctor(stdout: str) -> str:
    for line in stdout.splitlines():
        if line.strip().startswith("Status:"):
            return line.split(":", 1)[1].strip()
    return "unknown"


def summarize_regression(stdout: str) -> dict[str, Any]:
    summary = {
        "ok": False,
        "checkpoints": [],
        "screenshotDir": None,
    }
    payload_text = stdout.strip()
    if not payload_text:
        return summary
    start = payload_text.find("{")
    if start == -1:
        return summary
    try:
        payload = json.loads(payload_text[start:])
    except json.JSONDecodeError:
        return summary
    summary["ok"] = bool(payload.get("ok"))
    summary["checkpoints"] = [item.get("label") for item in payload.get("checkpoints", []) if isinstance(item, dict)]
    summary["screenshotDir"] = payload.get("screenshotDir")
    summary["states"] = payload.get("checkpoints", [])
    return summary


def write_if_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == content:
        return False
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def to_repo_relative(path_value: str | None) -> str | None:
    if not path_value:
        return None
    path = Path(path_value)
    try:
        return path.resolve().relative_to(REPO_ROOT.resolve()).as_posix()
    except Exception:
        return path.as_posix()


def render_markdown_report(report: dict[str, Any], markdown_report_path: Path) -> str:
    asset_summary = report.get("assetSummary") or {}
    regression = report.get("regressionSummary") or {}
    regression_dir_rel = to_repo_relative(regression.get("screenshotDir"))
    lines = [
        "# Asset Acceptance Report",
        "",
        "This file is auto-generated by `python asset_acceptance_check.py`.",
        "",
        f"- Overall: **{'OK' if report.get('ok') else 'FAIL'}**",
        f"- Asset placeholders pending: **{asset_summary.get('placeholders_pending', 'n/a')}**",
        f"- Replaced assets: **{asset_summary.get('replaced', 'n/a')}**",
        f"- Missing assets: **{asset_summary.get('missing_assets', 'n/a')}**",
        f"- Missing audio: **{asset_summary.get('missing_audio', 'n/a')}**",
        f"- Docs status: **{report.get('docsStatus', 'unknown')}**",
        f"- Asset status report: `{report.get('assetStatusReportPath')}`",
        "",
        "## Steps",
        "",
        "| Step | Result |",
        "| --- | --- |",
    ]
    for step in report.get("steps", []):
        lines.append(f"| `{step.get('name')}` | `{'OK' if step.get('ok') else 'FAIL'}` |")

    if regression:
        lines.extend(["", "## Frontend Regression", ""])
        lines.append(f"- Result: **{'OK' if regression.get('ok') else 'FAIL'}**")
        if regression.get("checkpoints"):
            lines.append("- Checkpoints:")
            for checkpoint in regression["checkpoints"]:
                lines.append(f"  - `{checkpoint}`")
        if regression_dir_rel:
            lines.append(f"- Screenshot directory: `{regression_dir_rel}`")

        states = regression.get("states") if isinstance(regression.get("states"), list) else []
        if states:
            lines.extend(["", "## Regression State Snapshots", ""])
            lines.append("| Checkpoint | Scene Phase | Worker | Bubble |")
            lines.append("| --- | --- | --- | --- |")
            for item in states:
                if not isinstance(item, dict):
                    continue
                label = item.get("label")
                state = item.get("state") if isinstance(item.get("state"), dict) else {}
                lines.append(
                    f"| `{label}` | `{state.get('scenePhase')}` | `{state.get('currentWorkerHeroId')}` | `{state.get('bubbleHeroId')}` |"
                )

        if regression_dir_rel:
            screenshot_files = sorted((REPO_ROOT / regression_dir_rel).glob("*.png"))
            if screenshot_files:
                lines.extend(["", "## Regression Screenshots", ""])
                for image_path in screenshot_files:
                    rel = image_path.resolve().relative_to(REPO_ROOT.resolve()).as_posix()
                    lines.append(f"### `{image_path.name}`")
                    lines.append("")
                    lines.append(f"![{image_path.name}](../{rel})")
                    lines.append("")

    failed_step = next((step for step in report.get("steps", []) if not step.get("ok")), None)
    if failed_step:
        lines.extend(["", "## Failure Output", ""])
        if failed_step.get("stdout"):
            lines.extend(["### Stdout", "", "```text", failed_step["stdout"], "```", ""])
        if failed_step.get("stderr"):
            lines.extend(["### Stderr", "", "```text", failed_step["stderr"], "```", ""])

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    configure_console_streams()
    parser = argparse.ArgumentParser(description="Run the full asset replacement acceptance flow.")
    parser.add_argument("--json", action="store_true", help="Emit machine-readable JSON")
    parser.add_argument(
        "--skip-regression",
        action="store_true",
        help="Skip browser regression checks (faster, but less strict)",
    )
    parser.add_argument(
        "--report-path",
        default=str(DEFAULT_MARKDOWN_REPORT_PATH),
        help="Write a markdown acceptance report to this path",
    )
    parser.add_argument(
        "--json-report-path",
        default=str(DEFAULT_JSON_REPORT_PATH),
        help="Write a JSON acceptance report to this path",
    )
    args = parser.parse_args()

    steps: list[dict[str, Any]] = []

    commands = [
        ("generate_asset_docs", [sys.executable, "generate_asset_docs.py"]),
        ("asset_delivery_doctor", [sys.executable, "asset_delivery_doctor.py"]),
        ("docs_consistency_doctor", [sys.executable, "docs_consistency_doctor.py"]),
        ("check_theme_consistency", [sys.executable, "check_theme_consistency.py"]),
    ]
    if not args.skip_regression:
        commands.append(("frontend_regression", [sys.executable, "brotherhood_control_runtime.py", "regression"]))

    for name, command in commands:
        result = run_command(command)
        result["name"] = name
        steps.append(result)
        if not result["ok"]:
            break

    asset_doctor_result = next((step for step in steps if step["name"] == "asset_delivery_doctor"), None)
    docs_result = next((step for step in steps if step["name"] == "docs_consistency_doctor"), None)
    regression_result = next((step for step in steps if step["name"] == "frontend_regression"), None)

    report = {
        "ok": all(step["ok"] for step in steps) and len(steps) == len(commands),
        "steps": steps,
        "assetSummary": summarize_asset_doctor(asset_doctor_result["stdout"]) if asset_doctor_result else {},
        "docsStatus": summarize_docs_doctor(docs_result["stdout"]) if docs_result else "unknown",
        "regressionSummary": summarize_regression(regression_result["stdout"]) if regression_result else None,
        "assetStatusReportPath": str(REPO_ROOT / "docs" / "asset-status.md"),
    }

    markdown_report_path = Path(args.report_path)
    json_report_path = Path(args.json_report_path)
    write_if_changed(markdown_report_path, render_markdown_report(report, markdown_report_path))
    write_if_changed(json_report_path, json.dumps(report, ensure_ascii=False, indent=2) + "\n")

    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
        return 0 if report["ok"] else 1

    print("Asset acceptance check")
    print("=" * 32)
    print(f"Overall: {'OK' if report['ok'] else 'FAIL'}")
    for step in steps:
        print(f"- {step['name']}: {'OK' if step['ok'] else 'FAIL'}")
    asset_summary = report["assetSummary"]
    if asset_summary:
        print(
            "Assets: placeholders_pending={placeholders_pending}, replaced={replaced}, missing_assets={missing_assets}, missing_audio={missing_audio}".format(
                **asset_summary
            )
        )
    print(f"Docs: {report['docsStatus']}")
    regression_summary = report["regressionSummary"]
    if regression_summary:
        print(f"Regression: {'OK' if regression_summary['ok'] else 'FAIL'}")
        if regression_summary.get("checkpoints"):
            print("  Checkpoints: " + ", ".join(regression_summary["checkpoints"]))
        if regression_summary.get("screenshotDir"):
            print(f"  Screenshots: {regression_summary['screenshotDir']}")
    print(f"Asset status report: {report['assetStatusReportPath']}")
    print(f"Acceptance markdown report: {markdown_report_path}")
    print(f"Acceptance JSON report: {json_report_path}")

    failed_step = next((step for step in steps if not step["ok"]), None)
    if failed_step:
        if failed_step["stdout"]:
            print("\nLast failing stdout:")
            print(failed_step["stdout"])
        if failed_step["stderr"]:
            print("\nLast failing stderr:")
            print(failed_step["stderr"])

    return 0 if report["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
