from __future__ import annotations

import argparse
import hashlib
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any

from check_theme_consistency import analyze_theme


REPO_ROOT = Path(__file__).resolve().parent
MANIFEST_PATH = REPO_ROOT / "frontend" / "themes" / "liangshan" / "asset-manifest.json"
DEFAULT_REPORT_PATH = REPO_ROOT / "docs" / "asset-status.md"


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def inspect_manifest(manifest: dict[str, Any]) -> dict[str, Any]:
    placeholder_assets = manifest.get("placeholderAssets") or []
    state_audio_files = manifest.get("stateAudioFiles") or []

    placeholder_results: list[dict[str, Any]] = []
    counts = Counter()
    for item in placeholder_assets:
        rel_path = item.get("path")
        path = REPO_ROOT / str(rel_path or "")
        status = "missing"
        actual_sha = None
        if path.exists():
            actual_sha = sha256_file(path)
            if actual_sha == item.get("placeholderSha256"):
                status = "placeholder"
            else:
                status = "replaced"
        counts[status] += 1
        placeholder_results.append(
            {
                "id": item.get("id"),
                "path": str(rel_path),
                "status": status,
                "description": item.get("description"),
                "scene": item.get("scene"),
                "heroId": item.get("heroId"),
                "category": item.get("category"),
                "requiresThemeSync": bool(item.get("requiresThemeSync")),
                "sha256": actual_sha,
            }
        )

    audio_results: list[dict[str, Any]] = []
    audio_counts = Counter()
    for rel_path in state_audio_files:
        path = REPO_ROOT / str(rel_path or "")
        status = "present" if path.exists() else "missing"
        audio_counts[status] += 1
        audio_results.append({"path": str(rel_path), "status": status})

    return {
        "placeholders": placeholder_results,
        "placeholderSummary": dict(counts),
        "audioFiles": audio_results,
        "audioSummary": dict(audio_counts),
    }


def group_placeholders_by_scene(report: dict[str, Any]) -> list[tuple[str, list[dict[str, Any]]]]:
    order = {"main": 0, "researching": 1, "writing": 2, "executing": 3, "syncing": 4, "error": 5}
    grouped: dict[str, list[dict[str, Any]]] = {}
    for item in report["placeholders"]:
        grouped.setdefault(item.get("scene") or "unknown", []).append(item)
    return sorted(grouped.items(), key=lambda item: (order.get(item[0], 99), item[0]))


def next_action_for(item: dict[str, Any]) -> str:
    status = item.get("status")
    needs_sync = bool(item.get("requiresThemeSync"))
    if status == "missing":
        return "create placeholder file at the exact path"
    if status == "placeholder":
        return "replace file, then review theme sync" if needs_sync else "replace file directly"
    if status == "replaced":
        return "review theme sync before shipping" if needs_sync else "ready"
    return "inspect manually"


def render_markdown_report(report: dict[str, Any], errors: list[str], warnings: list[str], theme_summary: dict[str, Any]) -> str:
    placeholder_summary = report["placeholderSummary"]
    audio_summary = report["audioSummary"]
    lines = [
        "# Asset Status",
        "",
        "This file is auto-generated by `python asset_delivery_doctor.py`.",
        "",
        "## Summary",
        "",
        f"- Placeholders still pending: **{placeholder_summary.get('placeholder', 0)}**",
        f"- Placeholder files already replaced: **{placeholder_summary.get('replaced', 0)}**",
        f"- Missing required asset slots: **{placeholder_summary.get('missing', 0)}**",
        f"- Missing state audio files: **{audio_summary.get('missing', 0)}**",
        f"- Support heroes in theme: **{theme_summary['supportHeroCount']}**",
        f"- Subscenes in theme: **{theme_summary['subsceneCount']}**",
        f"- Spritesheets in theme: **{theme_summary['spritesheetCount']}**",
        "",
        "## Fixed Workflow",
        "",
        "1. Replace the target file in-place using the exact path listed below.",
        "2. Run `python generate_asset_docs.py`.",
        "3. Run `python asset_delivery_doctor.py`.",
        "4. Run `python docs_consistency_doctor.py`.",
        "5. Run `python check_theme_consistency.py`.",
        "6. Run `python asset_acceptance_check.py` for the full acceptance pass.",
        "7. Open `docs/asset-acceptance-report.md` and review the generated screenshots.",
        "8. If the file is a spritesheet and frame size/count changed, sync `theme.json` before shipping.",
        "",
        "## Placeholder Inventory",
        "",
        "| Scene | Hero | Asset | Status | Theme Sync | Next Action |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for scene, items in group_placeholders_by_scene(report):
        for item in items:
            hero = item.get("heroId") or "-"
            sync = "Yes" if item.get("requiresThemeSync") else "No"
            lines.append(
                f"| `{scene}` | `{hero}` | `{item['path']}` | `{item['status']}` | {sync} | {next_action_for(item)} |"
            )

    lines.extend(
        [
            "",
            "## State Audio",
            "",
            "| File | Status |",
            "| --- | --- |",
        ]
    )
    for item in report["audioFiles"]:
        lines.append(f"| `{item['path']}` | `{item['status']}` |")

    if errors:
        lines.extend(["", "## Theme Consistency Errors", ""])
        lines.extend([f"- {line}" for line in errors])
    if warnings:
        lines.extend(["", "## Theme Consistency Warnings", ""])
        lines.extend([f"- {line}" for line in warnings])
    if not errors and not warnings:
        lines.extend(["", "## Theme Consistency", "", "- No consistency issues detected in this run."])
    lines.append("")
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == content:
        return False
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def print_human(report: dict[str, Any], errors: list[str], warnings: list[str], theme_summary: dict[str, Any]) -> int:
    placeholder_summary = report["placeholderSummary"]
    audio_summary = report["audioSummary"]
    pending = placeholder_summary.get("placeholder", 0)
    replaced = placeholder_summary.get("replaced", 0)
    missing = placeholder_summary.get("missing", 0)
    missing_audio = audio_summary.get("missing", 0)

    print("Asset delivery doctor")
    print(
        f"Summary: placeholders_pending={pending}, replaced={replaced}, "
        f"missing_assets={missing}, missing_audio={missing_audio}"
    )
    print(
        f"Theme: supportHeroes={theme_summary['supportHeroCount']}, "
        f"subscenes={theme_summary['subsceneCount']}, "
        f"spritesheets={theme_summary['spritesheetCount']}"
    )

    actionable = False

    if missing:
        actionable = True
        print("\nMissing required placeholder slots:")
        for item in report["placeholders"]:
            if item["status"] == "missing":
                print(f"- {item['path']} ({item['description']})")

    if pending:
        actionable = True
        print("\nStill using placeholder art:")
        for scene, items in group_placeholders_by_scene(report):
            pending_items = [item for item in items if item["status"] == "placeholder"]
            if not pending_items:
                continue
            print(f"  [{scene}]")
            for item in pending_items:
                sync_hint = "replace + sync theme" if item["requiresThemeSync"] else "replace directly"
                hero_suffix = f" / {item['heroId']}" if item.get("heroId") else ""
                print(f"  - {item['path']} ({item['description']}{hero_suffix}) -> {sync_hint}")

    replaced_needing_sync = [
        item for item in report["placeholders"] if item["status"] == "replaced" and item["requiresThemeSync"]
    ]
    if replaced_needing_sync:
        actionable = True
        print("\nReplaced assets that may need frame config review:")
        for item in replaced_needing_sync:
            print(f"- {item['path']} ({item['description']}) -> verify frame size/count in theme.json")

    if missing_audio:
        actionable = True
        print("\nMissing state audio files:")
        for item in report["audioFiles"]:
            if item["status"] == "missing":
                print(f"- {item['path']}")

    if errors:
        actionable = True
        print("\nTheme consistency errors:")
        for line in errors:
            print(f"- {line}")

    if warnings:
        print("\nTheme consistency warnings:")
        for line in warnings:
            print(f"- {line}")

    if not actionable:
        print("\nAsset workflow looks healthy. Next action: run the board and visually verify the latest replacement.")

    print("\nRecommended fixed workflow:")
    print("1. Replace files in-place using the exact manifest paths.")
    print("2. Run: python generate_asset_docs.py")
    print("3. Run: python asset_delivery_doctor.py")
    print("4. Run: python docs_consistency_doctor.py")
    print("5. Run: python check_theme_consistency.py")
    print("6. Run: python asset_acceptance_check.py")
    print("7. Open: docs/asset-acceptance-report.md")
    print("8. If a spritesheet changed frame size/count, sync theme.json before shipping.")
    print(f"\nDetailed status report: {DEFAULT_REPORT_PATH}")
    return 0 if not errors and not missing and not missing_audio else 1


def main() -> int:
    parser = argparse.ArgumentParser(description="Inspect Brotherhood-UI asset replacement readiness.")
    parser.add_argument("--manifest", default=str(MANIFEST_PATH), help="Path to asset-manifest.json")
    parser.add_argument("--json", action="store_true", help="Emit machine-readable JSON")
    parser.add_argument("--report-path", default=str(DEFAULT_REPORT_PATH), help="Write a markdown status report to this path")
    args = parser.parse_args()

    manifest_path = Path(args.manifest)
    if not manifest_path.exists():
        print(f"Manifest not found: {manifest_path}", file=sys.stderr)
        return 1

    manifest = load_json(manifest_path)
    report = inspect_manifest(manifest)
    errors, warnings, theme_summary = analyze_theme(REPO_ROOT / "frontend" / "themes" / "liangshan" / "theme.json")
    report_path = Path(args.report_path)
    report_markdown = render_markdown_report(report, errors, warnings, theme_summary)
    write_if_changed(report_path, report_markdown)

    if args.json:
        print(
            json.dumps(
                {
                    "ok": not errors and report["placeholderSummary"].get("missing", 0) == 0 and report["audioSummary"].get("missing", 0) == 0,
                    "manifest": str(manifest_path),
                    "report": report,
                    "themeErrors": errors,
                    "themeWarnings": warnings,
                    "themeSummary": theme_summary,
                    "reportPath": str(report_path),
                },
                ensure_ascii=False,
                indent=2,
            )
        )
        return 0 if not errors else 1

    return print_human(report, errors, warnings, theme_summary)


if __name__ == "__main__":
    raise SystemExit(main())
